maplogs/urls.py
from django.urls import path
from . import views

app_name = 'maps'

handler404 = 'maplogs.views.page_not_found'
urlpatterns = [
    path('', views.map_list, name='map_list'),
    path('search', views.search, name='search'),
    path('details/<int:map_id>', views.map_details, name='map_details'),
    path('filter/rims', views.map_filter_rim, name='map_filter_rim'),
    path('filter/pdp', views.map_filter_pdp, name='map_filter_pdp'),
    path('filter/cadastral', views.map_filter_cadastral, name='map_filter_cadastral'),
    path('filter/county', views.filter_by_county, name='filter_by_county'),
    path('getmap/<int:map_id>/', views.get_map, name='get_map'),
]

registry/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('maplogs.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

maplogs/models.py
from django.db import models
# from django.db.models.fields.files import ImageField
from django.urls import reverse
from PIL import Image


class Map(models.Model):
    map_category_choices = [
        ('Cadastral', 'cadastral map'),
        ('General Boundary', 'general boundary'),
        ('PDP', 'pdp')
    ]

    county_choices = [
        ('Laikipia', 'Laikipia'),
        ('Nakuru', 'Nakuru'),
        ('Nyeri', 'Nyeri'),
        ('Nyandarua', 'Nyandarua'),
    ]

    title = models.CharField(max_length=200)
    scanned = models.BooleanField()
    upload_date = models.DateField(auto_now=True)
    stamped_county_date = models.DateField(auto_now=False, auto_now_add=False)
    county = models.CharField(max_length=50, choices=county_choices, default='Nyandarua')
    map_category = models.CharField(max_length=100, choices=map_category_choices, default='General Boundary')
    image = models.ImageField(upload_to='maps/%Y/%m/%d', blank=True)
    # thumbnail = models.ImageField(upload_to='maps/%Y/%m/%d', blank=True)

    class Meta:
        ordering = ('-stamped_county_date',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('maps:map_details', args=[self.id])

    def get_thumbnail(self):
        if self.thumbnail:
            return reverse('maps:map_detail, ')
        else:
            if self.image:
                self.thumbnail = self.make_thumbnail(self.image)
                self.save()

                return self.thumbnail
            else:
                return ''

    def make_thumbnail(self, image, size=(300, 200)):
        img = Image.open(image)
        img.convert('RGB')
        img.thumbnail(size)
        img.save('JPEG', quality=85)


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=100, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name', )
        index_together = (('id', 'slug'), )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('maps:product_detail', args=[self.id, self.slug])


''' 
1. create a new advanced search
2. how to handle redundant maps

'''

maplogs/forms.py
from django import forms


class GetMapForm(forms.Form):
    name = forms.CharField(max_length=50)
    email = forms.EmailField()

maplogs/views.py
# from django import template
from django.http.response import Http404
# from django.shortcuts import render, get_object_or_404
# from django.http import HttpResponse
# from django.template import loader
# import datetime

from . models import Map
from .forms import GetMapForm
from django.core.mail import send_mail

# to do
'''
    display all available maps and make queries and the scanned status and dates
    create maps orders or requests and download for scanned maps
    if map is hardcopy request a print in advance i.e send a request(text/email) to the printing people

    and make payments

    admin
    add maps scanned and soft copies
'''

from django.shortcuts import render


def page_not_found(request, exception):
    return render(request, 'maps/404.html', {})


def map_list(request):
    maps = Map.objects.all()
    return render(request, 'maps/map_list.html', {'maps': maps})


def map_filter_rim(request):
    maps = Map.objects.filter(map_category='General Boundary')
    return render(request, 'maps/map_list.html', {'maps': maps})


def map_filter_pdp(request):
    maps = Map.objects.filter(map_category='PDP')
    return render(request, 'maps/map_list.html', {'maps': maps})


def map_filter_cadastral(request):
    maps = Map.objects.filter(map_category='Cadastral')
    return render(request, 'maps/map_list.html', {'maps': maps})


def filter_by_county(request):
    """filter by county names"""
    try:
        maps = Map.objects.filter(county__icontains=request.GET.get('county'))
        return render(request, 'maps/map_list.html', {'maps': maps})
    except Map.DoesNotExist:
        raise Http404('404 no such county')


def search(request):
    """search title of maps by any name"""
    print(request.GET.get('search'))
    query = request.GET.get('search')
    
    try:
        maps = Map.objects.filter(title__icontains=query)
    except Map.DoesNotExist:
        raise Http404('404 map not available')
        # return render(request, 'maps/map_list.html', {'maps': maps})
    
    context = {
        'maps': maps
    }

    return render(request, 'maps/map_list.html', context)


def map_details(requests, map_id):
    
    try:
        maps = Map.objects.get(pk=map_id)
    except Map.DoesNotExist:
        # raise Http404('404 you seem lost')
        return render(requests, 'maps/404.html', {'map_id': map_id})
    context = {

        'map': maps
        
    }
    return render(requests, 'maps/map_detail.html', context)


def get_map(request, map_id):
    map_sent = False

    if request.method == 'POST':
        form = GetMapForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            map_ = Map.objects.get(pk=map_id)
            subject = f"{map_.title}"
            message = f"find the attached map {map_.title}"
            send_mail(subject, message, 'info@geomird.co.ke', [cd['email']])

            map_sent = True

    else:
        form = GetMapForm()
    return render(request, 'maps/get_map.html', {'form': form,
                                                 'map_sent': map_sent})

maplogs/templates/maps/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} geomird_maps {% endblock %}</title>
    <link rel="stylesheet" href="{% static 'maps/base.css' %}">
    <link rel="stylesheet" href="{% static 'maps/base.css' %}">
</head>
<body>
    <div class="header">
        <h1>Geomird Maps</h1>
        <a href="https://geomird.co.ke" class="logo">
            <img src="{% static 'img/logo.svg' %}" alt="">
        </a>
        <form action="{% url 'maps:search' %}" method="get">
            <input type="text" placeholder="search for map" name="search">
            <input type="submit" value="search">
            <!-- <button type="submit">search</button> -->
        </form>
    </div>

    <div class="sidebar">
        <ul>
            <h5>Map type</h5>
            <li><a href="{% url 'maps:map_filter_rim' %}">RIMs</a></li>
            <li><a href="{% url 'maps:map_filter_cadastral' %}">Cadastral</a></li>
            <li><a href="{% url 'maps:map_filter_pdp' %}">PDP</a></li>

            <h5>County</h5>
            <form action="{% url 'maps:filter_by_county' %}" method="get">
                <input type="text" placeholder="filter by county" name="county">
                <input type="submit" value="filter">
                <!-- <button type="submit">search</button> -->
            </form>
        </ul>
    </div>

    <div class="main">
        {% block body %}
        {% endblock %}
    </div>
    
    
</body>
</html>

maplogs/templates/maps/get_map.html
{% extends 'maps/base.html' %}

{% block body %}
{% if map_sent %}
<p> map was sent to {{ form.cleaned_data.email }}</p>

{% else %}
<form method="post">
  {% csrf_token %}
  {{ form.as_table }}

  <input type="submit" value="getmap">
</form>
{% endif %}


{% endblock %}

maplogs/templates/maps/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"> -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="{% static 'maps/base.css' %}">
    
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    
    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <title>Maplogs</title>
</head>
<body>
    <div class="row">
        <!-- <div class="column"> -->
            <h1>Maplogs</h1>
            <form action="{% url 'maps:search' %}" method="get" class="form">
                <!-- {% csrf_token %} -->
                <!-- <label for="search">map you wanna search</label><br> -->
                <input type="text" name="search" id="search">
                <br>
                <input type="submit" value="search">
            </form>
        <!-- </div> -->
    </div>
</body>
</html>

maplogs/templates/maps/list.html
{% extends "maps/base.html" %}

{% load static %}

{% block title %} 
    {% if category %} {{ category.name}} {% else %} Products {% endif %}
{% endblock %}

{% block content %} 
<div id="sidebar">
    <h3>Categories</h3>

    <ul>
        <li {% if not category %} class="selected" {% endif %}>
            <a href="{% url "maps:product_list" %}">All</a>
        </li>
        {% for c in categories %}
        <li {% if category.slug == c.slug %} class="selected" {% endif %}>
            <a href="{{ c.get_absolute_url }}">{{c.name }}</a>
        </li>
        {% endfor %}

    </ul>
</div>

<div id="main" class="product_list">
    <h1>{% if category %} {{ category.name }} {% else %} Products {% endif %}</h1>

    {% for product in products %}
    <div class="item">
        <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.image %} {{ product.image }} {% else %} 
            {% static 'img/no_image.svg' %} {% endif %}"  alt="" srcset="">
        </a>

        <a href="{{ product.get_absolute_url }}">{{product.name }}</a>
        <br>
        {{ product.price }}
    </div>
    {% endfor %}
</div>
{% endblock %}

maplogs/templates/maps/map_detail.html
{% extends 'maps/base.html' %}
{% load static %}

<link rel="stylesheet" href="static/base.css">
<link rel="stylesheet" href="{% static 'maps/base.css' %}">
{% block title %} {{ map.title }} {% endblock %}

{% block body %}

<div class="map_details">
    <h4 >
        {{ map.title }}
    </h4>

    <p>
        aquired on <strong>{{ map.stamped_county_date }}</strong>
    </p>
    {% if not map.image %}
    <p>request a hard copy its present</p>
    {% else %}
    <a href="{% url 'maps:get_map' map.id %}">Get Map</a>
    {% endif %}
    
    <img src="{% if map.image %} {{ map.image.url }} {% else %} {% static 'img/no_image.svg' %} {% endif %}" alt="" srcset="" class="map_image">
    
    
</div>


{% endblock %}

maplogs/templates/maps/map_list.html
{% extends 'maps/base.html' %}
{% load static %}

<link rel="stylesheet" href="{% static 'maps/base.css' %}">
<link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
{% block title %} map list {% endblock %}

{% block body %}

<table class="maps table">
    <tr>
        <th>Map Title</th>
        <th>Date</th>
        <th>Category</th>
        <th>County</th>
    </tr>
    {% for map in maps %}
    <tr>
        <td><a href="{{ map.get_absolute_url }}">{{ map.title }}</a></td>
        <td>{{ map.stamped_county_date }}</td>
        <td>{{ map.map_category }}</td>
        <td>{{ map.county }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}

maplogs/templates/maps/search.html
{% load static %}

<style>
    table{
        /* border: 1px solid; */
        width: 75%;
        border-collapse: collapse;
        margin: auto;
        margin-top: 50px;
    }

    th, td{
        border-bottom: 1px solid  #ddd;
        padding-top: 12px;
        padding-bottom: 12px;
    }

    th{
        height: 50px;
        background-color: #4CAF50;
        color: white;
    }

    td{
        text-align: left;
    }

    tr:hover{
        background-color: rgb(103, 103, 107);
    }

    /* table links  */

    a{
        text-decoration: none;
    }

    a:hover{
        text-decoration: brown;
    }
</style>
<link rel="stylesheet" href="{% static 'maps/base.css' %}">
<div style="overflow-x:auto;">
    <table>
        <tr>
            <th>Map Title</th>
            <th>County</th>
            <th>Date</th>
            <th>Scanned</th>
            <th>Download</th>
        </tr>
        
        {% if all_maps %}
        
        {% for map in all_maps %}
        <tr>
            <td><a href="{% url 'maps:map_details' map.id %}">{{ map.title }}</a></td>

            <td>{{ map.county }}</td>
            
            <td>{{ map.stamped_county_date }}</td>
    
            <td>{{ map.scanned }}</td>
    
            <td>
                {% if map.scanned == True %}
                <a href="#">Download</a>
                {% else %}
                Download
                {% endif %}
            </td>
    
        
        </tr>
    
        {% endfor %}
    
        {% else %}
    
                <p>no such map</p>
        
        {% endif %}
    
    </table>
</div>

<br>